/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import agent.TronRunner;
import agent.WallAgent;
import jade.core.AID;
import java.awt.Color;
import java.awt.Container;
import java.awt.LayoutManager;
import java.io.Serializable;

/**
 *
 * @author 09952410905
 */
public class GroundPanel extends javax.swing.JPanel implements Serializable {

    private AID tronRunner = null;
    
    public GroundPanel(Color color, LayoutManager layout) {        
        this.setBackground(color);
        this.setLayout(layout);
        initComponents();
    }
    
    public boolean hasTronRunner() {
        return (tronRunner == null) ? false : true;
    }
    
    public AID getTronRunner() {
        return this.tronRunner;
    }
    
    public void setTronRunner(AID runner) {
        this.tronRunner = runner;
    }
    
    public void removeTronRunner() {
        this.tronRunner = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
